version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: Clinicms-db
    environment:
      MYSQL_ROOT_PASSWORD: Aditya@@09
      MYSQL_DATABASE: Clinicms
      MYSQL_USER: root
      MYSQL_PASSWORD: Aditya@@09
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build: .
    container_name: Clinicms-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clinicms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: aditya
    ports:
      - "8084:8084"

volumes:
  mysql_data:
